<a href="https://colab.research.google.com/github/Athrudev/Athrudev/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Begginer Tutorial for Numpy**


**why we use Numpy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]]) #we can create a simple array by using 'array'

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[0,1])

2


In [ ]:
print(arr.shape) #The shape of an array is the number of elements in each dimension.

(2, 3)


In [ ]:
print(arr.dtype) #it will return datatype of the array

int64


#**Array creation:** Conversion from other python structures

In [ ]:
l_arr=np.array([[1,2,3],[4,5,6],[8,9,0]])
print(l_arr)

[[1 2 3]
 [4 5 6]
 [8 9 0]]


In [ ]:
print(l_arr.shape)

(3, 3)


In [ ]:
print(l_arr.size)

9


#**Array creation:**Intrinsic array creation object

**zeros attribute**

In [ ]:
x=int(input("Enter X:"))
y=int(input("Enter Y:"))
zeroes=np.zeros((x,y))
print(zeroes)
print(zeroes.shape)
print(zeroes.size)
#The numpy.zeros() function returns a new array of given shape and type, with zeros.

Enter X:5
Enter Y:2
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
(5, 2)
10


**arange() function**

In [ ]:
rng=np.arange(15)
print(rng)
print(np.arange(4).reshape(2,2))
print(np.arange(4,10))
print(np.arange(1,15,3))
#Returns an array with evenly spaced elements as per the interval

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[0 1]
 [2 3]]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


**linspace() function**

In [ ]:
lnspace=np.linspace(1,50,10)
print(lnspace)
#linspace Return evenly spaced numbers over a specified interval.

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


**empty() & empty_like() function**

In [ ]:
emp=np.empty((2,2))
print(emp)
print(np.empty_like(lnspace))
#empty() Return an empty array with shape and type of input.
#empty_like() function return a new array with the same shape and data type as the one passed to it

[[ 1.         17.33333333]
 [33.66666667 50.        ]]
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [ ]:
rav=np.arange(1,21)
print(rav)
rav=rav.reshape(10,2)
print(rav)
rav=rav.ravel()
print(rav)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
